# Generated by Django 3.2.16 on 2022-11-01 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_doc', models.FileField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(default='Delhi', max_length=200, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_doc', models.FileField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='User_Auth',
            fields=[
                ('email_id', models.CharField(default='na', max_length=200, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(default='na', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ViewAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.medicaldocuments')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_decided', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('user_type', models.CharField(default='na', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user_auth')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_doc', models.FileField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medicaldocuments',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_doc', models.FileField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(default='Delhi', max_length=200, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Infirmary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_doc', models.FileField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(default='Delhi', max_length=200, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
