# Generated by Django 3.2.16 on 2022-11-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldocuments',
            old_name='hospital',
            new_name='verifier',
        ),
        migrations.RemoveField(
            model_name='medicaldocuments',
            name='patient',
        ),
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(default='na', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_1',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='infirmary',
            name='description',
            field=models.TextField(default='na', null=True),
        ),
        migrations.AddField(
            model_name='infirmary',
            name='image_1',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='infirmary',
            name='image_2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='infirmary',
            name='wallet',
            field=models.IntegerField(default=1000000, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='description',
            field=models.TextField(default='na', null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='image_1',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='image_2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='wallet',
            field=models.IntegerField(default=1000000, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocuments',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_auth'),
        ),
        migrations.AddField(
            model_name='patient',
            name='wallet',
            field=models.IntegerField(default=1000000, null=True),
        ),
        migrations.AddField(
            model_name='user_auth',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user_auth'),
        ),
        migrations.AlterField(
            model_name='infirmary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user_auth'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user_auth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user_auth'),
        ),
        migrations.AlterField(
            model_name='viewaccess',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_auth'),
        ),
        migrations.CreateModel(
            name='InsuranceRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.IntegerField(default=0, null=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.medicaldocuments')),
                ('insurance_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.insurancecompany')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='InfirmaryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(default='na', null=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.medicaldocuments')),
                ('infirmary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.infirmary')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DocRequestHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fulfilled', models.BooleanField(default=False, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
