# Generated by Django 4.1.2 on 2022-11-26 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221125_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.medicaldocuments')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.docrequesthospital')),
            ],
        ),
    ]
