# Generated by Django 4.1.2 on 2022-11-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221127_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infirmary',
            name='wallet',
            field=models.PositiveIntegerField(default=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='wallet',
            field=models.PositiveIntegerField(default=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='wallet',
            field=models.PositiveIntegerField(default=1000000, null=True),
        ),
    ]
