# Generated by Django 4.1.2 on 2022-11-26 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221123_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='fullname',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator('[!@#$%^&*()_+-=~`[]{}|;\\\'",./<>?]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=models.CharField(default='Delhi', max_length=200, null=True, validators=[django.core.validators.RegexValidator('[!@#$%^&*()_+-=~`[]{}|;\\\'",./<>?]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='infirmary',
            name='fullname',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator('[!@#$%^&*()_+-=~`[]{}|;\\\'",./<>?]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='infirmary',
            name='location',
            field=models.CharField(default='Delhi', max_length=200, null=True, validators=[django.core.validators.RegexValidator('[!@#$%^&*()_+-=~`[]{}|;\\\'",./<>?]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='fullname',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator('[!@#$%^&*()_+-=~`[]{}|;\\\'",./<>?]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='location',
            field=models.CharField(default='Delhi', max_length=200, null=True, validators=[django.core.validators.RegexValidator('[!@#$%^&*()_+-=~`[]{}|;\\\'",./<>?]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fullname',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator('[!@#$%^&*()_+-=~`[]{}|;\\\'",./<>?]', inverse_match=True)]),
        ),
    ]
