# Generated by Django 3.2.16 on 2022-11-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221125_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='is_verified',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='infirmary',
            name='is_verified',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='is_verified',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_verified',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
