# Generated by Django 4.1.2 on 2022-11-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221123_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_auth',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
