# Generated by Django 3.2.16 on 2022-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_infirmary_wallet_alter_insurancecompany_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infirmaryorder',
            name='is_fulfilled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
