# Generated by Django 4.1.2 on 2022-11-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_docrequesthospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldocuments',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='medicaldocuments',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicaldocuments',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_auth'),
        ),
    ]
