# Generated by Django 4.1.2 on 2022-11-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_medicaldocuments_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocuments',
            name='verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hospital'),
        ),
    ]
