# Generated by Django 4.1.2 on 2022-10-27 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_hospital_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_doc', models.FileField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(default='Delhi', max_length=200, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Infirmary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_doc', models.FileField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(default='Delhi', max_length=200, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
