# Generated by Django 4.1.2 on 2022-10-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_insurancecompany_infirmary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_doc', models.FileField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
