# Generated by Django 4.1.2 on 2022-10-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_viewaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='na', max_length=200)),
                ('email_id', models.CharField(default='na', max_length=200)),
                ('password_hash', models.CharField(default='na', max_length=512)),
            ],
        ),
    ]
