# Generated by Django 4.1.2 on 2022-10-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_patient_wallet_infirmaryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='infirmary',
            name='wallet',
            field=models.IntegerField(default=1000000, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='wallet',
            field=models.IntegerField(default=1000000, null=True),
        ),
    ]
