# Generated by Django 4.1.2 on 2022-10-29 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_infirmary_wallet_insurancecompany_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.IntegerField(default=0, null=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.medicaldocuments')),
                ('insurance_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.insurancecompany')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
