# Generated by Django 4.1.2 on 2022-11-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_insurancerefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(default='na', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_1',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='infirmary',
            name='description',
            field=models.TextField(default='na', null=True),
        ),
        migrations.AddField(
            model_name='infirmary',
            name='image_1',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='infirmary',
            name='image_2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='description',
            field=models.TextField(default='na', null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='image_1',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='image_2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
